name: Github Pages CI

on: [push, pull_request]

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.6'
          cache: 'npm'
      - run: npm ci
      - name: Deploy to GH Pages
        env:
          GH_TOKEN: eclass:${{ secrets.GH_TOKEN }}
        run: npm run deploy-storybook -- --out=docs --source-branch=main
